### ISSUE TITLE
0xffffffff is rendered as 0x10000000000000000

### ISSUE THREAD

**Issue by abitrolly** [kaitai-io/kaitai_struct_webide#121] opened 2020-08-05 18:24 UTC
KSY.
```
      - id: xattr_id_table_start
        type: u8
```
Binary.
```
ff ff ff ff ff ff ff ff
```
Object tree.
```
xattrIdTableStart = 0x10000000000000000 = 18446744073709552000
```
Looks like a bug to me.

![image](https://user-images.githubusercontent.com/8781107/89449567-f0349980-d761-11ea-8d07-8c06de2436d6.png)

**Comment by generalmimon** [comment] 2020-08-05 19:55
It's not actually bug of the Web IDE, but of the JavaScript itself (it's probably by design, but it's really annoying in these cases). 

The JavaScript [runtime library](https://github.com/kaitai-io/kaitai_struct_javascript_runtime/blob/master/KaitaiStream.js#L356-L368) (and the JavaScript code generated by KSC) works with native JS numbers, and native JS `number` type cannot exactly represent integers less than **-(2<sup>53</sup> - 1)** ([Number.MIN_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER)) and greater than **-2<sup>53</sup> - 1** ([Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)). If the stored value is outside that safe range, you can silently lose precision during the conversion to the native JS `number` type.

Closing, because it's a duplicate of https://github.com/kaitai-io/kaitai_struct/issues/183.

**Closed by generalmimon** 2020-08-05 19:55 UTC
Labels: duplicate
