### ISSUE TITLE
Sometimes some modules are timed out (an exception is thrown by loader) and the IDE doesn't work

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_webide#45] opened 2017-09-26 13:33 UTC
http://requirejs.org/docs/api.html#config-waitSeconds

**Comment by generalmimon** [comment] 2022-02-24 08:34
Duplicate of https://github.com/kaitai-io/kaitai_struct_webide/issues/37

**Closed by generalmimon** 2022-02-24 08:34 UTC
Labels: bug, duplicate
