### ISSUE TITLE
[feature suggestion] Autorun

### ISSUE THREAD

**Issue by jumpjack** [kaitai-io/kaitai_struct_webide#141] opened 2022-06-30 17:13 UTC
The autorun feature is interesting... but sometimes annoying: of course the parsing keeps failing until you end writing a structure, not to mention if the file to parse is very long, which completely locks the parser, with last (possibly invalid) error message remaining visible, and without warnings about parsing being in progress.

A "run" button and and "autorun"  checkbox (or "parse" and "autoparse") would improve the experience a lot.

**Comment by KOLANICH** [comment] 2022-06-30 17:47
Dupe of #44

**Comment by generalmimon** [comment] 2022-06-30 17:50
https://github.com/kaitai-io/kaitai_struct_webide/issues/44#issuecomment-362430799:

> Please use https://ide.kaitai.io/devel/?noAutoCompile and press "Ctrl+Enter" in the .ksy editor to trigger recompilation manually.

Wait, how come I don't know about this?

**Closed** 2022-06-30 18:30 UTC
