### ISSUE TITLE
Problem with imports on local storage

### ISSUE THREAD

**Issue by ghost** [kaitai-io/kaitai_struct_webide#59] opened 2018-02-09 16:02 UTC
I created a trivial example in WebIDE consisting from two files, `foo.ksy` and `example.ksy`, with the following content:
```yaml
meta:
  id: foo
  endian: le

seq:
  - id: foo_seq
    type: u2

```
and
```yaml
meta:
  id: example
  endian: le
  imports:
    - foo

seq:
  - id: bar
    type: u2
  - id: baz
    type: foo
```
Both files are on local storage. If `example.ksy` is opened and I reload the page then IDE show the following error:
```
Parse error: undefined
Call stack: undefined TypeError: Foo is not a constructor
```
The object tree remains empty after the error. I have to open `foo.ksy` and then go back to `example.ksy` to clear this error and rebuild the tree. Is this some kind of a bug?

**Comment by koczkatamas** [comment] 2018-02-13 11:41
Sorry, I did not have time to look into the problem, but if I remember correctly the import handling is not working correctly in the WebIDE, more info can be found in this issue: https://github.com/kaitai-io/kaitai_struct_webide/issues/30

There is a chance that it was fixed in the planned V2, but the development stuck a little now.

**Comment by generalmimon** [comment] 2020-09-14 21:18
_Following my [comment on Gitter](https://gitter.im/kaitai_struct/Lobby?at=5f5e4cc7b468994d0d282d23):_

I investigated the bug, and the cause is pretty simple: the imported KS types are sometimes used before their definition in the generated code. It doesn't matter whether the imports are relative or absolute. For example, this spec:

```yaml
meta:
  id: imports_abs
  # this will import "/common/bcd.ksy"
  imports:
    - /common/bcd
seq:
  - id: a
    type: bcd(4, 8, true)
```

compiles to this:

```javascript
(function (root, factory) {
  // ...
  root.ImportsAbs = factory(root.KaitaiStream, root.Bcd); // (1)
  // ...
}(this, function (KaitaiStream, Bcd) {
var ImportsAbs = (function() {
  // ...
  ImportsAbs.prototype._read = function() {
    this.a = new Bcd(this._io, this, null, 4, 8, true); // (2)
  }
  // ...
})();
return ImportsAbs;
}));

(function (root, factory) {
  // ...
  root.Bcd = factory(root.KaitaiStream);
  // ...
}(this, function (KaitaiStream) {
var Bcd = (function() { /* ... */ })();
return Bcd;
}));
```

As you can see, the type `ImportsAbs` depends on `Bcd` type, but the `Bcd` type is defined after `ImportAbs`. This implies that at the time of `ImportsAbs` definition, `root.Bcd` is `undefined` (1), and this value will be passed into the closure as the `Bcd` parameter. This causes the error `Bcd is not a constructor` on line (2). In fact, this is what happens:

```javascript
(function(Bcd) {
  // ...
  new Bcd();
  // ...
})(undefined);
```

The problem is in the way how Web IDE handles the generated JS files which originated from imported KSY files. As you can see from this line:

https://github.com/kaitai-io/kaitai_struct_webide/blob/5d9fb119933464ec1a17d65964cdaa3ed6a98dca/src/v1/app.ts#L103

..., it just concatenates the JS files received from the [compiler](https://www.npmjs.com/package/kaitai-struct-compiler) in no particular order. In practice, this will *probably* match the order in which the Scala.js KSC build requests KSY files, but there are no guarantees. 

Unfortunately, this order will be mostly wrong, because the imported types will usually occur before the types that use them.

## A dirty "solution" (redefining the types multiple times)

A dirty solution how to work around this would be evaluate the whole generated code multiple times: for the first time, some class dependencies might be `undefined` at the time when they're used, but on the second run, the classes are *more likely* to be already defined from the first run. I say *more likely*, not *definitely*, because a case like this can also happen:

```javascript
var Foo = (function(Bar) {
    return (function() {
        this.bar = new Bar();
    });
})(Bar);
var Bar = (function(Baz) {
    return (function() {
        this.baz = new Baz();
    });
})(Baz);
var Baz = (function() {
    return (function() {
        this.prop = 5;
    });
})();
```

The dependency tree looks like this:

```
Foo
 └─ Bar
     └─ Baz
```

When you run the snippet for the first time and then try initializing the classes, this is what happens:

```javascript
new Foo(); // Uncaught TypeError: Bar is not a constructor
new Bar(); // Uncaught TypeError: Baz is not a constructor
new Baz(); // => {prop: 5}
```

When you execute the definitions for the second time, it turns out like this:

```javascript
new Foo(); // Uncaught TypeError: Baz is not a constructor
new Bar(); // => {baz: {prop: 5}}
new Baz(); // => {prop: 5}
```

As you can guess, to make the `Foo` class work, it'd be necessary to redefine the classes for the **3rd time**, and then it finally works:

```javascript
new Foo(); // => {bar: {baz: {prop: 5}}}
```

So this dirty ugly workaround can't be considered a working solution.

However, this is how currently works the workaround. When you compile the spec using imported types for the first time, only types with no dependencies are guaranteed to work (most often, they _will_ be the only ones which properly work). On the second run (e.g. when you press `Ctrl` + `Enter` for example), the fully-working types with no dependencies will be already registered in the `kaitaiWorker.js` global scope from the first run, so now will certainly work also the types dependent only on types with no dependencies, and so on.

## A naive solution

The naive solution is to ensure that every imported type has been already defined at the time when any other type imports that type. To do that, it's necessary to find dependent types of each imported type.

A definition of a type can come at the current point in time in the resulting code only if all its dependencies have been already defined. This already leads to a fairly simple algorithm. A type can be defined first if and only if it has no dependencies.

However, this means that if there isn't a single type having no dependencies, no type can come first if we want to ensure that there are no type is referenced before its definition. There is no correct order, and thus there is IMHO no way how to ensure that the resulting code will always work without taking advantage of some sort of type declaration hoisting. In other words, it's needed to defer referencing any types until all types are declared.

## The proper solution

The problem with the current UMD module is that it references all dependencies of the particular type at the time of its definition; it just pulls the current value from `root.Bcd`, and no matter if it is `undefined` or not, the value is fixed in the closure parameter `Bcd`. There needs to be some sort of [hoisting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function#Function_declaration_hoisting):

```javascript
const scope = {};
(function(scope) {
    scope.Foo = function(noBar) {
        if (!noBar) {
            this.bar = new scope.Bar();
        }
    };
})(scope);

(function(scope) {
    scope.Bar = function() {
        this.foo = new scope.Foo(true);
    };
})(scope);

console.log(new scope.Foo(false)); // => Foo{ bar: Bar{ foo: Foo{} } }
```

Here, the dependencies of types are referenced at the time of instantiation, not their definition, so it works even despite the fact there's a recursive dependency.

So we need to defer referencing the types when the KSC-generated JS code is using this UMD module envelope:

```javascript
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['kaitai-struct/KaitaiStream', './Bcd'], factory);
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory(require('kaitai-struct/KaitaiStream'), require('./Bcd'));
  } else {
    root.ImportsAbs = factory(root.KaitaiStream, root.Bcd); // this is currently the branch used in the Web IDE
  }
}(this, function (KaitaiStream, Bcd) {
  // ...
```

As we found out, the currently used `else` branch is not applicable. Can we help ourselves by opting another `if` branch? The first AMD `define()` branch looks promising, because we could make a custom `define()` function that would suit our purposes.

This is the signature of `define()` function as specified by the [AMD standard](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#define-function-):

```javascript
define(id?, dependencies?, factory);
```

A minor problem with the `define` invocation is that we have no idea under which name we should register a factory function:

```javascript
define(['kaitai-struct/KaitaiStream', './Bcd'], factory);
```

The `factory` function is defined as `(function (KaitaiStream, Bcd) {})`. The naive idea would be to ask for [`factory.name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name), but this works only for named functions, not anonymous ones (quite logically). So declaring the `factory` like `(function ImportsAbs(KaitaiStream, Bcd) {})` would solve this problem (`(function ImportsAbs(KaitaiStream, Bcd) {}).name` returns `"ImportsAbs"`).

This implies a minor change in KSC, but I think it's pretty harmless. Naming the function passed as parameter behaves like a [named function expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function#Named_function_expression). In short, the function will be accessible under its name only in its definition (this allows e.g. recursive calls). However, this implicit local "variable" can be normally shadowed by a variable with the same name (even when using `const`), and the KSC-generated code won't reference `ImportsAbs` identifier inside the `ImportsAbs` class definition, so this also doesn't have to be solved.

If we don't want to make changes to the KSC-generated code, we can paste some helper code when concatenating the types:

```javascript
wi.currentKsyType = "ImportsAbs";
(function (root, factory) {
  // ...
  define(['kaitai-struct/KaitaiStream', './Bcd'], factory);
  // ...
}(this, function (KaitaiStream, Bcd) {
var ImportsAbs = (function() { /* ... */ })();
return ImportsAbs;
}));

wi.currentKsyType = "Bcd";
(function (root, factory) {
  // ...
  define(['kaitai-struct/KaitaiStream'], factory);
  // ...
}(this, function (KaitaiStream) {
var Bcd = (function() { /* ... */ })();
return Bcd;
}));
```

Then the `define()` function can query the `wi.currentKsyType` value as well, and thus know under which name to register the currently processed `factory` function. However, these `wi.currentKsyType = ...` helpers would have to appear also in the `JS code (debug)` tab in the Web IDE, which will look awkward, and if some user deletes it, the type resolving would break, so this is probably not a good idea. Naming the `factory` function seems more sensible.

**Closed** 2024-02-21 15:51 UTC
